#include "CreateInstanceDialog.hpp"
#include "Language.hpp"
#include "Loaders.hpp"
#include "PackBrowser.hpp"
#include "ModRepository.hpp"
#include <QtWidgets>
#include <QtConcurrent>
namespace {QString t(const char *s){return Language::key(QString::fromUtf8(s));}}
CreateInstanceDialog::CreateInstanceDialog(McInstanceManager *manager,const QList<McVersion> &catalog,const QJsonArray &packs,const McInstance &source,bool copy,QWidget *parent):QDialog(parent),m_manager(manager),m_catalog(catalog){
    setObjectName("createInstanceDialog");setWindowTitle(t("New instance"));resize(980,750);setMinimumSize(790,640);auto outer=new QVBoxLayout(this);outer->setSpacing(12);
    auto header=new QHBoxLayout;outer->addLayout(header);m_icon=new QComboBox;m_icon->setObjectName("instanceIcon");for(auto pair:{qMakePair("Grass",QStyle::SP_DirHomeIcon),qMakePair("World",QStyle::SP_DriveNetIcon),qMakePair("Mods",QStyle::SP_FileDialogContentsView),qMakePair("Adventure",QStyle::SP_ComputerIcon)})m_icon->addItem(style()->standardIcon(pair.second),t(pair.first),QString(pair.first));header->addWidget(m_icon);
    auto details=new QFormLayout;header->addLayout(details,1);m_name=new QLineEdit(copy?source.name+" (2)":"");m_name->setObjectName("instanceName");details->addRow(t("Name"),m_name);m_group=new QComboBox;m_group->setEditable(true);m_group->setObjectName("instanceGroup");m_group->addItem(t("No group"),"");QSet<QString> groups;for(auto i:manager->instances()){try{auto g=ModRepository::read(i.dir+"/instance.json")["group"].toString();if(!g.isEmpty())groups.insert(g);}catch(...){}}for(auto g:groups)m_group->addItem(g,g);details->addRow(t("Group"),m_group);
    auto body=new QHBoxLayout;outer->addLayout(body,1);auto sources=new QListWidget;sources->setFixedWidth(158);sources->setObjectName("instanceSources");sources->addItems({t("Custom"),t("My packs"),t("Import"),"ATLauncher","CurseForge","FTB","FTB Legacy",t("Import FTB App"),"Modrinth","Technic"});sources->setCurrentRow(0);body->addWidget(sources);
    auto right=new QVBoxLayout;body->addLayout(right,1);m_status=new QLabel(t("Choose Minecraft, then a compatible mod loader."));m_status->setWordWrap(true);right->addWidget(m_status);
    auto gameArea=new QHBoxLayout;right->addLayout(gameArea,1);auto game=new QVBoxLayout;gameArea->addLayout(game,1);m_versions=new QTreeWidget;m_versions->setObjectName("minecraftVersions");m_versions->setColumnCount(3);m_versions->setHeaderLabels({t("Version"),t("Release date"),t("Type")});m_versions->setRootIsDecorated(false);m_versions->setSelectionMode(QAbstractItemView::SingleSelection);m_versions->header()->setSectionResizeMode(0,QHeaderView::Stretch);m_versions->header()->setSectionResizeMode(1,QHeaderView::ResizeToContents);m_versions->setMinimumHeight(160);game->addWidget(m_versions,1);m_search=new QLineEdit;m_search->setObjectName("versionSearch");m_search->setPlaceholderText(t("Search versions…"));game->addWidget(m_search);
    auto filters=new QVBoxLayout;gameArea->addLayout(filters);filters->addWidget(new QLabel(t("Filter")));for(auto entry:{qMakePair("release","Releases"),qMakePair("snapshot","Snapshots"),qMakePair("old_beta","Betas"),qMakePair("old_alpha","Alphas")}){auto c=new QCheckBox(t(entry.second));c->setObjectName(QString(entry.first)+"Filter");c->setChecked(QString(entry.first)=="release");m_types[entry.first]=c;filters->addWidget(c);connect(c,&QCheckBox::toggled,this,[this]{populateVersions();});}filters->addStretch();auto refresh=new QPushButton(t("Refresh"));filters->addWidget(refresh);connect(refresh,&QPushButton::clicked,this,[this]{m_status->setText(t("Checking versions…"));m_manager->fetchManifest();});
    auto loaderArea=new QHBoxLayout;right->addLayout(loaderArea,1);auto versions=new QVBoxLayout;loaderArea->addLayout(versions,1);m_loaderStatus=new QLabel;m_loaderStatus->setWordWrap(true);versions->addWidget(m_loaderStatus);m_loaders=new QListWidget;m_loaders->setObjectName("loaderVersions");m_loaders->setMinimumHeight(125);versions->addWidget(m_loaders,1);m_loaderSearch=new QLineEdit;m_loaderSearch->setPlaceholderText(t("Search loader versions…"));versions->addWidget(m_loaderSearch);connect(m_loaderSearch,&QLineEdit::textChanged,this,[this](QString query){for(int i=0;i<m_loaders->count();++i)m_loaders->item(i)->setHidden(!m_loaders->item(i)->text().contains(query,Qt::CaseInsensitive));});
    auto choices=new QVBoxLayout;loaderArea->addLayout(choices);choices->addWidget(new QLabel(t("Mod loader")));auto buttons=new QButtonGroup(this);for(auto kind:{"vanilla","neoforge","forge","fabric","quilt"}){auto key=QString(kind);auto title=key=="vanilla"?t("None"):key=="neoforge"?QString("NeoForge"):key.left(1).toUpper()+key.mid(1);auto radio=new QRadioButton(title);radio->setObjectName(key+"Loader");buttons->addButton(radio);choices->addWidget(radio);radio->setChecked(key=="vanilla");connect(radio,&QRadioButton::clicked,this,[this,key]{m_loader=key;fetchLoaders();});}choices->addStretch();auto reload=new QPushButton(t("Refresh"));choices->addWidget(reload);connect(reload,&QPushButton::clicked,this,[this]{fetchLoaders();});
    auto options=new QFormLayout;outer->addLayout(options);m_pack=new QComboBox;m_pack->setObjectName("initialPack");m_pack->addItem(t("No pack"));for(auto v:packs)m_pack->addItem(v.toObject()["name"].toString(),v.toObject());options->addRow(t("Initial pack"),m_pack);if(copy)m_pack->setEnabled(false);m_memory=new QSpinBox;m_memory->setRange(512,65536);m_memory->setSingleStep(512);m_memory->setValue(copy?source.xmx:4096);m_memory->setSuffix(" MB");options->addRow(t("Maximum memory"),m_memory);
    auto note=new QLabel(t("Java is detected automatically. Instances keep separate worlds, mods and settings."));note->setWordWrap(true);outer->addWidget(note);m_buttons=new QDialogButtonBox(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);m_buttons->button(QDialogButtonBox::Ok)->setText(t("Create instance"));outer->addWidget(m_buttons);connect(m_buttons,&QDialogButtonBox::accepted,this,[this]{validate();if(m_buttons->button(QDialogButtonBox::Ok)->isEnabled())accept();});connect(m_buttons,&QDialogButtonBox::rejected,this,&QDialog::reject);
    connect(m_name,&QLineEdit::textChanged,this,[this]{validate();});connect(m_search,&QLineEdit::textChanged,this,[this]{populateVersions();});connect(m_versions,&QTreeWidget::currentItemChanged,this,[this]{fetchLoaders();});connect(m_loaders,&QListWidget::currentRowChanged,this,[this]{validate();});
    connect(manager,&McInstanceManager::manifestReady,this,[this](QList<McVersion> versions){m_catalog=versions;populateVersions();m_status->setText(t("Choose Minecraft, then a compatible mod loader."));});connect(manager,&McInstanceManager::manifestFailed,this,[this](QString error){m_status->setText(Language::message(error));});
    connect(sources,&QListWidget::currentRowChanged,this,[this](int row){
        if(row==0){m_providerPack={};m_providerVersion={};m_status->setText(t("Choose Minecraft, then a compatible mod loader."));validate();return;}
        if(row==1){m_providerPack={};m_providerVersion={};m_pack->setFocus();m_pack->showPopup();validate();return;}
        if(row==2){auto file=QFileDialog::getOpenFileName(this,t("Import"),{},"Modpacks (*.mrpack *.zip *.json)");if(file.isEmpty())return;
            if(file.endsWith(".json",Qt::CaseInsensitive)){try{auto pack=ModRepository::read(file);if(pack["schema"].toInt()!=1||!pack["projects"].isArray()||pack["name"].toString().isEmpty())throw std::runtime_error("Invalid EBALIA pack");m_pack->addItem(pack["name"].toString(),pack);m_pack->setCurrentIndex(m_pack->count()-1);m_providerPack={};}catch(const std::exception &e){QMessageBox::warning(this,"EBALIA",QString::fromUtf8(e.what()));}}
            else{m_providerPack={{"provider","import"},{"path",file}};m_providerVersion={};if(m_name->text().isEmpty())m_name->setText(QFileInfo(file).completeBaseName());m_status->setText(t("The pack defines the Minecraft version and mod loader."));}validate();return;
        }
        if(row==7){auto folder=QFileDialog::getExistingDirectory(this,t("Choose the FTB App instance folder"),QDir::homePath()+"/.ftba/instances");if(folder.isEmpty())return;if(!QFile::exists(folder+"/instance.json")){QMessageBox::warning(this,"EBALIA",t("This folder does not contain an FTB App instance."));return;}m_providerPack={{"provider","import_ftb"},{"path",folder}};m_providerVersion={};if(m_name->text().isEmpty()){try{m_name->setText(ModRepository::read(folder+"/instance.json")["name"].toString());}catch(...){}}m_status->setText(t("The pack defines the Minecraft version and mod loader."));validate();return;}
        const QMap<int,QString> providers{{3,"atlauncher"},{4,"curseforge"},{5,"ftb"},{6,"legacy_ftb"},{8,"modrinth"},{9,"technic"}};auto provider=providers.value(row);if(provider.isEmpty())return;
        PackBrowser browser(QFileInfo(m_manager->mcDir()).absolutePath(),provider,this);if(browser.exec()!=QDialog::Accepted)return;m_providerPack=browser.selectedPack;m_providerVersion=browser.selectedVersion;m_name->setText(m_providerPack["name"].toString());m_status->setText(m_providerPack["name"].toString()+" · "+m_providerVersion["name"].toString()+"\n"+t("The pack defines the Minecraft version and mod loader."));validate();
    });

    if(copy)for(auto v:catalog)if(v.id==source.mcVersion&&m_types.contains(v.type))m_types[v.type]->setChecked(true);populateVersions();if(copy){for(int i=0;i<m_versions->topLevelItemCount();++i)if(m_versions->topLevelItem(i)->text(0)==source.mcVersion)m_versions->setCurrentItem(m_versions->topLevelItem(i));if(auto radio=findChild<QRadioButton*>(source.loader+"Loader"))radio->click();}validate();
}
void CreateInstanceDialog::populateVersions(){
    auto selected=m_versions->currentItem()?m_versions->currentItem()->text(0):QString();QSignalBlocker block(m_versions);m_versions->clear();QTreeWidgetItem *keep=nullptr;for(auto v:m_catalog){if(!m_types.contains(v.type)||!m_types[v.type]->isChecked()||!v.id.contains(m_search->text(),Qt::CaseInsensitive))continue;auto item=new QTreeWidgetItem(m_versions,{v.id,v.releaseTime,Language::key(v.type=="release"?"Release":v.type=="snapshot"?"Snapshot":v.type=="old_beta"?"Beta":"Alpha")});if(v.id==selected)keep=item;}if(!keep&&m_versions->topLevelItemCount())keep=m_versions->topLevelItem(0);m_versions->setCurrentItem(keep);block.unblock();fetchLoaders();
}
void CreateInstanceDialog::fetchLoaders(){
    ++m_request;m_loading=false;m_loaders->clear();m_loaderSearch->clear();if(!m_versions->currentItem()){m_loaderStatus->setText(t("Choose a Minecraft version."));validate();return;}
    if(m_loader=="vanilla"){m_loaderStatus->setText(t("No mod loader selected. Vanilla uses the original game."));validate();return;}
    auto game=m_versions->currentItem()->text(0),loader=m_loader;int id=m_request;m_loading=true;m_loaderStatus->setText(t("Checking compatible loader versions…"));validate();auto watcher=new QFutureWatcher<QJsonObject>(this);
    connect(watcher,&QFutureWatcher<QJsonObject>::finished,this,[this,watcher,id]{auto result=watcher->result();watcher->deleteLater();if(id!=m_request)return;m_loading=false;if(result.contains("error")){m_loaderStatus->setText(result["error"].toString());validate();return;}for(auto v:result["versions"].toArray())m_loaders->addItem(v.toString());m_loaderStatus->setText(m_loaders->count()?t("Choose a loader version."):t("No compatible loader versions found."));if(m_loaders->count())m_loaders->setCurrentRow(0);validate();});
    watcher->setFuture(QtConcurrent::run([loader,game]{try{QJsonArray versions;for(auto v:Loaders::versions(loader,game))versions.append(v);return QJsonObject{{"versions",versions}};}catch(const std::exception &e){return QJsonObject{{"error",QString::fromUtf8(e.what())}};}}));
}
void CreateInstanceDialog::validate(){if(!m_buttons)return;m_buttons->button(QDialogButtonBox::Ok)->setEnabled(!m_name->text().trimmed().isEmpty()&&(!m_providerPack.isEmpty()||(m_versions->currentItem()&&!m_loading&&(m_loader=="vanilla"||m_loaders->currentItem()))));}
QJsonObject CreateInstanceDialog::configuration()const{return {{"name",m_name->text().trimmed()},{"mcVersion",m_versions->currentItem()?m_versions->currentItem()->text(0):QString()},{"providerPack",m_providerPack},{"providerVersion",m_providerVersion},{"loader",m_loader},{"loaderVersion",m_loaders->currentItem()?m_loaders->currentItem()->text():QString()},{"group",m_group->currentIndex()==0&&m_group->currentText()==t("No group")?QString():m_group->currentText().trimmed()},{"icon",m_icon->currentData().toString()},{"xmx",m_memory->value()},{"pack",m_pack->currentData().toJsonObject()}};}
