#include "PackBrowser.hpp"
#include "PackService.hpp"
#include "Language.hpp"
#include <QtWidgets>
#include <QtConcurrent>
PackBrowser::PackBrowser(const QString &root,const QString &provider,QWidget *parent):QDialog(parent){
    auto tr=[](const char *s){return Language::key(s);};setWindowTitle(provider);resize(820,600);auto layout=new QVBoxLayout(this);auto search=new QLineEdit;search->setPlaceholderText(tr("Search modpacks…"));layout->addWidget(search);auto status=new QLabel;status->setWordWrap(true);layout->addWidget(status);auto results=new QListWidget;results->setWordWrap(true);layout->addWidget(results,1);auto versions=new QComboBox;layout->addWidget(versions);auto controls=new QDialogButtonBox(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);controls->button(QDialogButtonBox::Ok)->setText(tr("Use this modpack"));controls->button(QDialogButtonBox::Ok)->setEnabled(false);auto find=controls->addButton(tr("Search"),QDialogButtonBox::ActionRole);auto more=controls->addButton(tr("Load more"),QDialogButtonBox::ActionRole);more->setVisible(provider=="modrinth"||provider=="curseforge");layout->addWidget(controls);connect(controls,&QDialogButtonBox::rejected,this,&QDialog::reject);connect(controls,&QDialogButtonBox::accepted,this,[this,versions]{selectedVersion=versions->currentData().toJsonObject();if(!selectedPack.isEmpty()&&!selectedVersion.isEmpty())accept();});
    auto epoch=std::make_shared<int>(0);auto page=std::make_shared<int>(0);auto activeQuery=std::make_shared<QString>();
    auto lookup=[=,this](bool append){++*epoch;auto ticket=*epoch;controls->button(QDialogButtonBox::Ok)->setEnabled(false);find->setEnabled(false);more->setEnabled(false);if(!append){*page=0;*activeQuery=search->text();results->clear();versions->clear();selectedPack={};}else ++*page;status->setText(tr("Loading modpacks…"));auto watcher=new QFutureWatcher<QJsonObject>(this);connect(watcher,&QFutureWatcher<QJsonObject>::finished,this,[=,this]{auto d=watcher->result();watcher->deleteLater();if(ticket!=*epoch)return;find->setEnabled(true);more->setEnabled(true);if(d.contains("error")){status->setText(d["error"].toString());return;}for(auto v:d["packs"].toArray()){auto p=v.toObject();QTextDocument text;text.setHtml(p["description"].toString());auto item=new QListWidgetItem(p["name"].toString()+"\n"+text.toPlainText().left(250),results);item->setData(Qt::UserRole,p);}status->setText(QString::number(results->count())+" · "+tr("Choose a modpack and its version."));});auto query=*activeQuery;auto offset=*page;watcher->setFuture(QtConcurrent::run([root,provider,query,offset]{try{return QJsonObject{{"packs",PackService(root).search(provider,query,offset)}};}catch(const std::exception &e){return QJsonObject{{"error",QString::fromUtf8(e.what())}};}}));};
    connect(find,&QPushButton::clicked,this,[lookup]{lookup(false);});connect(more,&QPushButton::clicked,this,[lookup]{lookup(true);});connect(search,&QLineEdit::returnPressed,this,[lookup]{lookup(false);});
    connect(results,&QListWidget::currentItemChanged,this,[=,this](QListWidgetItem *item){++*epoch;auto ticket=*epoch;versions->clear();controls->button(QDialogButtonBox::Ok)->setEnabled(false);if(!item)return;selectedPack=item->data(Qt::UserRole).toJsonObject();status->setText(tr("Loading versions…"));auto watcher=new QFutureWatcher<QJsonObject>(this);auto pack=selectedPack;connect(watcher,&QFutureWatcher<QJsonObject>::finished,this,[=]{auto d=watcher->result();watcher->deleteLater();if(ticket!=*epoch)return;if(d.contains("error")){status->setText(d["error"].toString());return;}for(auto v:d["versions"].toArray())versions->addItem(v.toObject()["name"].toString(),v.toObject());controls->button(QDialogButtonBox::Ok)->setEnabled(versions->count()>0);status->setText(tr("Choose a modpack and its version."));});watcher->setFuture(QtConcurrent::run([root,pack]{try{return QJsonObject{{"versions",PackService(root).versions(pack)}};}catch(const std::exception &e){return QJsonObject{{"error",QString::fromUtf8(e.what())}};}}));});
    if(!qEnvironmentVariableIsSet("EBALIA_NO_NETWORK"))QTimer::singleShot(0,this,[lookup]{lookup(false);});
}
